"""empty message

Revision ID: 085560e07ac5
Revises: ecbc226c3b6d
Create Date: 2021-11-09 00:17:06.658991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085560e07ac5'
down_revision = 'ecbc226c3b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('description', table_name='projects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('description', 'projects', ['description'], unique=True)
    # ### end Alembic commands ###
