"""empty message

Revision ID: 0a16393fdaab
Revises: 085560e07ac5
Create Date: 2021-11-09 00:17:53.570371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a16393fdaab'
down_revision = '085560e07ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='projects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'projects', ['name'], unique=True)
    # ### end Alembic commands ###
