"""Created at not nullable

Revision ID: 2096c2f7f813
Revises: a858d236c43f
Create Date: 2021-08-20 00:45:01.677694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2096c2f7f813'
down_revision = 'a858d236c43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('role_assignments', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('volume_types', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('volumes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volumes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('volume_types', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('role_assignments', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
