"""added volume params

Revision ID: 5832ac54175e
Revises: 35148bde975e
Create Date: 2021-08-11 23:25:58.520738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5832ac54175e'
down_revision = '35148bde975e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volumes', sa.Column('size', sa.Integer(), nullable=False))
    op.add_column('volumes', sa.Column('type', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volumes', 'type')
    op.drop_column('volumes', 'size')
    # ### end Alembic commands ###
