"""Added active column

Revision ID: 6f2ee36a0412
Revises: 3c2cfa410f10
Create Date: 2021-08-19 23:57:30.542985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2ee36a0412'
down_revision = '3c2cfa410f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_assignments', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_assignments', 'active')
    # ### end Alembic commands ###
